version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    image: ksiksimohamedarafet-5sim4-tpfoyer
    ports:
      - "8083:8082"  # Mapping host port 8083 to container port 8082
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - mynetwork

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  ngrok:  # Move ngrok inside the services section
    image: wernight/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2YOSNkCjz3Viq8BfpIbc9kN24xd_3ioqQMeR5LjDtLHJ8XLNG  # Optional but recommended
    command: /bin/ngrok http host.docker.internal:8080  # Use full path for the ngrok executable
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
