version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    image: ksiksimohamedarafet-5sim4-tpfoyer
    ports:
      - "8083:8082"  # Mapping host port 8082 to container port 8080
    depends_on:
      - mysql-db  # Ensures MySQL container starts before Spring Boot app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mydb  # Correct MySQL connection URL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - mynetwork

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb  # This ensures that the "mydb" database is created
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
